name: docker.aws-deploy

on:
  push:
    branches: 
      - main
    paths:
      - .github/workflows/docker-aws-deploy.yml
      - aws-deploy/**

env:
  # Format
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  IMAGE: aws-deploy


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    defaults:
      run:
        working-directory: aws-deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download release tool
        run: |
          wget -q https://drive.google.com/file/d/1MUMEI83hjuJsjoPVRJls3tIgysBGwCI8/view?usp=share_link -O release.zip
          unzip release.zip

      - name: Extract Docker metadata
        id: meta
        run: echo "tag=ghcr.io/$REPOSITORY-$IMAGE:$(./release latest --any | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64 \
            --tag ${{ steps.meta.outputs.tag }} \
            --push .
